#![allow(dead_code)]

pub const RAW_UHDM_ACTUAL: u32 = 2001;
pub const RAW_UHDM_ACTUAL_GROUP: u32 = 2002;
pub const RAW_UHDM_ACTUAL_TYPESPEC: u32 = 2003;
pub const RAW_UHDM_ALIAS_STMT: u32 = 2004;
pub const RAW_UHDM_ALIAS_STMTS: u32 = 2005;
pub const RAW_UHDM_ALWAYS: u32 = 2012;
pub const RAW_UHDM_ANY_PATTERN: u32 = 2013;
pub const RAW_UHDM_ARGUMENTS: u32 = 2014;
pub const RAW_UHDM_ARRAY_EXPR: u32 = 2015;
pub const RAW_UHDM_ARRAY_NET: u32 = 2016;
pub const RAW_UHDM_ARRAY_NETS: u32 = 2017;
pub const RAW_UHDM_ARRAY_TYPESPEC: u32 = 2018;
pub const RAW_UHDM_ARRAY_VAR: u32 = 2019;
pub const RAW_UHDM_ARRAY_VAR_MEMS: u32 = 2020;
pub const RAW_UHDM_ARRAY_VARS: u32 = 2021;
pub const RAW_UHDM_ASSERT_STMT: u32 = 2022;
pub const RAW_UHDM_ASSERTION: u32 = 2023;
pub const RAW_UHDM_ASSERTIONS: u32 = 2024;
pub const RAW_UHDM_ASSIGN_STMT: u32 = 2025;
pub const RAW_UHDM_ASSIGNMENT: u32 = 2026;
pub const RAW_UHDM_ASSUME: u32 = 2027;
pub const RAW_UHDM_ATOMIC_STMT: u32 = 2028;
pub const RAW_UHDM_ATTRIBUTE: u32 = 2029;
pub const RAW_UHDM_ATTRIBUTES: u32 = 2030;
pub const RAW_UHDM_BASE_EXPR: u32 = 2031;
pub const RAW_UHDM_BASE_TYPESPEC: u32 = 2032;
pub const RAW_UHDM_BEGIN: u32 = 2033;
pub const RAW_UHDM_BIT_SELECT: u32 = 2034;
pub const RAW_UHDM_BIT_TYPESPEC: u32 = 2035;
pub const RAW_UHDM_BIT_VAR: u32 = 2036;
pub const RAW_UHDM_BITS: u32 = 2037;
pub const RAW_UHDM_BREAK_STMT: u32 = 2038;
pub const RAW_UHDM_BYTE_TYPESPEC: u32 = 2039;
pub const RAW_UHDM_BYTE_VAR: u32 = 2040;
pub const RAW_UHDM_CASE_ITEM: u32 = 2041;
pub const RAW_UHDM_CASE_ITEMS: u32 = 2042;
pub const RAW_UHDM_CASE_PROPERTY: u32 = 2043;
pub const RAW_UHDM_CASE_PROPERTY_ITEM: u32 = 2044;
pub const RAW_UHDM_CASE_PROPERTY_ITEMS: u32 = 2045;
pub const RAW_UHDM_CASE_STMT: u32 = 2046;
pub const RAW_UHDM_CAST_TO_EXPR: u32 = 2047;
pub const RAW_UHDM_CHANDLE_TYPESPEC: u32 = 2048;
pub const RAW_UHDM_CHANDLE_VAR: u32 = 2049;
pub const RAW_UHDM_CHECKER_DECL: u32 = 2050;
pub const RAW_UHDM_CHECKER_INST: u32 = 2051;
pub const RAW_UHDM_CHECKER_INST_PORT: u32 = 2052;
pub const RAW_UHDM_CHECKER_PORT: u32 = 2053;
pub const RAW_UHDM_CLASS_DEFN: u32 = 2054;
pub const RAW_UHDM_CLASS_DEFNS: u32 = 2055;
pub const RAW_UHDM_CLASS_OBJ: u32 = 2056;
pub const RAW_UHDM_CLASS_TYPESPEC: u32 = 2057;
pub const RAW_UHDM_CLASS_TYPESPECS: u32 = 2058;
pub const RAW_UHDM_CLASS_VAR: u32 = 2059;
pub const RAW_UHDM_CLOCKED_PROPERTY: u32 = 2060;
pub const RAW_UHDM_CLOCKED_SEQ: u32 = 2061;
pub const RAW_UHDM_CLOCKED_SEQS: u32 = 2062;
pub const RAW_UHDM_CLOCKING_BLOCK: u32 = 2063;
pub const RAW_UHDM_CLOCKING_BLOCKS: u32 = 2064;
pub const RAW_UHDM_CLOCKING_EVENT: u32 = 2065;
pub const RAW_UHDM_CLOCKING_IO_DECL: u32 = 2066;
pub const RAW_UHDM_CLOCKING_IO_DECLS: u32 = 2067;
pub const RAW_UHDM_CONCURRENT_ASSERTIONS: u32 = 2068;
pub const RAW_UHDM_CONDITION: u32 = 2069;
pub const RAW_UHDM_CONSTANT: u32 = 2070;
pub const RAW_UHDM_CONSTR_FOREACH: u32 = 2071;
pub const RAW_UHDM_CONSTR_IF: u32 = 2072;
pub const RAW_UHDM_CONSTR_IF_ELSE: u32 = 2073;
pub const RAW_UHDM_CONSTRAINT: u32 = 2074;
pub const RAW_UHDM_CONSTRAINT_EXPR: u32 = 2075;
pub const RAW_UHDM_CONSTRAINT_EXPRS: u32 = 2076;
pub const RAW_UHDM_CONSTRAINT_ITEM_GROUP: u32 = 2077;
pub const RAW_UHDM_CONSTRAINT_ITEMS: u32 = 2078;
pub const RAW_UHDM_CONSTRAINT_ORDERING: u32 = 2079;
pub const RAW_UHDM_CONSTRAINTS: u32 = 2080;
pub const RAW_UHDM_CONT_ASSIGN: u32 = 2081;
pub const RAW_UHDM_CONT_ASSIGN_BIT: u32 = 2082;
pub const RAW_UHDM_CONT_ASSIGN_BITS: u32 = 2083;
pub const RAW_UHDM_CONT_ASSIGNS: u32 = 2084;
pub const RAW_UHDM_CONTINUE_STMT: u32 = 2085;
pub const RAW_UHDM_COVER: u32 = 2086;
pub const RAW_UHDM_DEASSIGN: u32 = 2087;
pub const RAW_UHDM_DEF_PARAM: u32 = 2088;
pub const RAW_UHDM_DEF_PARAMS: u32 = 2089;
pub const RAW_UHDM_DEFAULT_CLOCKING: u32 = 2090;
pub const RAW_UHDM_DEFAULT_VALUE: u32 = 2091;
pub const RAW_UHDM_DELAY: u32 = 2092;
pub const RAW_UHDM_DELAY_CONTROL: u32 = 2093;
pub const RAW_UHDM_DELAY_TERM: u32 = 2094;
pub const RAW_UHDM_DERIVEDS: u32 = 2095;
pub const RAW_UHDM_DESIGN: u32 = 2096;
pub const RAW_UHDM_DISABLE: u32 = 2097;
pub const RAW_UHDM_DISABLE_FORK: u32 = 2098;
pub const RAW_UHDM_DISABLES: u32 = 2099;
pub const RAW_UHDM_DIST_ITEM: u32 = 2100;
pub const RAW_UHDM_DIST_ITEMS: u32 = 2101;
pub const RAW_UHDM_DISTRIBUTION: u32 = 2102;
pub const RAW_UHDM_DO_WHILE: u32 = 2103;
pub const RAW_UHDM_DRIVERS: u32 = 2104;
pub const RAW_UHDM_ELAB_TASKS: u32 = 2105;
pub const RAW_UHDM_ELEM_TYPESPEC: u32 = 2106;
pub const RAW_UHDM_ELEMENTS: u32 = 2107;
pub const RAW_UHDM_ELSE_CONSTRAINT_EXPRS: u32 = 2108;
pub const RAW_UHDM_ELSE_STMT: u32 = 2109;
pub const RAW_UHDM_ENUM_CONST: u32 = 2110;
pub const RAW_UHDM_ENUM_CONSTS: u32 = 2111;
pub const RAW_UHDM_ENUM_NET: u32 = 2112;
pub const RAW_UHDM_ENUM_STRUCT_PACKED_NET_GROUP: u32 = 2113;
pub const RAW_UHDM_ENUM_STRUCT_UNION_PACKED_ARRAY_TYPESPEC_GROUP: u32 = 2114;
pub const RAW_UHDM_ENUM_STRUCT_UNION_PACKED_VAR_GROUP: u32 = 2115;
pub const RAW_UHDM_ENUM_TYPESPEC: u32 = 2116;
pub const RAW_UHDM_ENUM_VAR: u32 = 2117;
pub const RAW_UHDM_EVENT_CONTROL: u32 = 2118;
pub const RAW_UHDM_EVENT_STMT: u32 = 2119;
pub const RAW_UHDM_EVENT_TYPESPEC: u32 = 2120;
pub const RAW_UHDM_EXPECT_STMT: u32 = 2121;
pub const RAW_UHDM_EXPR: u32 = 2122;
pub const RAW_UHDM_EXPR_CONSTR_GROUP: u32 = 2123;
pub const RAW_UHDM_EXPR_DIST: u32 = 2124;
pub const RAW_UHDM_EXPR_INDEX: u32 = 2125;
pub const RAW_UHDM_EXPR_INDEXES: u32 = 2126;
pub const RAW_UHDM_EXPR_INTERF_EXPR_GROUP: u32 = 2127;
pub const RAW_UHDM_EXPR_RANGE_GROUP: u32 = 2128;
pub const RAW_UHDM_EXPR_REF_OBJ_GROUP: u32 = 2129;
pub const RAW_UHDM_EXPR_SEQUENCE_INST_GROUP: u32 = 2130;
pub const RAW_UHDM_EXPR_SEQUENCE_INST_NAMED_EVENT_GROUP: u32 = 2131;
pub const RAW_UHDM_EXPR_TCHK_TERM_GROUP: u32 = 2132;
pub const RAW_UHDM_EXPR_TCHK_TERMS: u32 = 2133;
pub const RAW_UHDM_EXPR_TYPESPEC_GROUP: u32 = 2134;
pub const RAW_UHDM_EXPRESSIONS: u32 = 2135;
pub const RAW_UHDM_EXPRS: u32 = 2136;
pub const RAW_UHDM_EXTENDS: u32 = 2137;
pub const RAW_UHDM_FINAL_STMT: u32 = 2138;
pub const RAW_UHDM_FOR_STMT: u32 = 2139;
pub const RAW_UHDM_FORCE: u32 = 2140;
pub const RAW_UHDM_FOREACH_STMT: u32 = 2141;
pub const RAW_UHDM_FOREVER_STMT: u32 = 2142;
pub const RAW_UHDM_FORK_STMT: u32 = 2143;
pub const RAW_UHDM_FUNC_CALL: u32 = 2144;
pub const RAW_UHDM_FUNCTION: u32 = 2145;
pub const RAW_UHDM_FUNCTIONS: u32 = 2146;
pub const RAW_UHDM_GATE: u32 = 2147;
pub const RAW_UHDM_GATE_ARRAY: u32 = 2148;
pub const RAW_UHDM_GEN_CASE: u32 = 2149;
pub const RAW_UHDM_GEN_FOR: u32 = 2150;
pub const RAW_UHDM_GEN_IF: u32 = 2151;
pub const RAW_UHDM_GEN_IF_ELSE: u32 = 2152;
pub const RAW_UHDM_GEN_REGION: u32 = 2153;
pub const RAW_UHDM_GEN_SCOPE: u32 = 2154;
pub const RAW_UHDM_GEN_SCOPE_ARRAY: u32 = 2155;
pub const RAW_UHDM_GEN_SCOPE_ARRAYS: u32 = 2156;
pub const RAW_UHDM_GEN_SCOPES: u32 = 2157;
pub const RAW_UHDM_GEN_STMT: u32 = 2158;
pub const RAW_UHDM_GEN_STMTS: u32 = 2159;
pub const RAW_UHDM_GEN_VAR: u32 = 2160;
pub const RAW_UHDM_GLOBAL_CLOCKING: u32 = 2161;
pub const RAW_UHDM_HIER_PATH: u32 = 2162;
pub const RAW_UHDM_HIGH_CONN: u32 = 2163;
pub const RAW_UHDM_IF_ELSE: u32 = 2164;
pub const RAW_UHDM_IF_STMT: u32 = 2165;
pub const RAW_UHDM_IMMEDIATE_ASSERT: u32 = 2166;
pub const RAW_UHDM_IMMEDIATE_ASSUME: u32 = 2167;
pub const RAW_UHDM_IMMEDIATE_COVER: u32 = 2168;
pub const RAW_UHDM_IMPLICATION: u32 = 2169;
pub const RAW_UHDM_IMPORT_TYPESPEC: u32 = 2170;
pub const RAW_UHDM_INCLUDE_FILE_INFO: u32 = 2171;
pub const RAW_UHDM_INCLUDE_FILE_INFOS: u32 = 2172;
pub const RAW_UHDM_INDEX: u32 = 2173;
pub const RAW_UHDM_INDEX_TYPESPEC: u32 = 2174;
pub const RAW_UHDM_INDEXED_PART_SELECT: u32 = 2175;
pub const RAW_UHDM_INDEXES: u32 = 2176;
pub const RAW_UHDM_INITIAL: u32 = 2177;
pub const RAW_UHDM_INPUT_SKEW: u32 = 2178;
pub const RAW_UHDM_INSTANCE: u32 = 2179;
pub const RAW_UHDM_INSTANCE_ARRAY: u32 = 2180;
pub const RAW_UHDM_INSTANCE_ITEM: u32 = 2181;
pub const RAW_UHDM_INSTANCE_ITEMS: u32 = 2182;
pub const RAW_UHDM_INSTANCES: u32 = 2183;
pub const RAW_UHDM_INT_TYPESPEC: u32 = 2184;
pub const RAW_UHDM_INT_VAR: u32 = 2185;
pub const RAW_UHDM_INTEGER_NET: u32 = 2186;
pub const RAW_UHDM_INTEGER_TYPESPEC: u32 = 2187;
pub const RAW_UHDM_INTEGER_VAR: u32 = 2188;
pub const RAW_UHDM_INTERF_PROG_MOD_GROUP: u32 = 2189;
pub const RAW_UHDM_INTERFACE_ARRAY: u32 = 2190;
pub const RAW_UHDM_INTERFACE_ARRAYS: u32 = 2191;
pub const RAW_UHDM_INTERFACE_EXPR: u32 = 2192;
pub const RAW_UHDM_INTERFACE_INST: u32 = 2193;
pub const RAW_UHDM_INTERFACE_TF_DECL: u32 = 2194;
pub const RAW_UHDM_INTERFACE_TF_DECLS: u32 = 2195;
pub const RAW_UHDM_INTERFACE_TYPESPEC: u32 = 2196;
pub const RAW_UHDM_INTERFACES: u32 = 2197;
pub const RAW_UHDM_IO_DECL: u32 = 2198;
pub const RAW_UHDM_IO_DECLS: u32 = 2199;
pub const RAW_UHDM_ITEM: u32 = 2200;
pub const RAW_UHDM_LEFT_EXPR: u32 = 2201;
pub const RAW_UHDM_LEFT_RANGE: u32 = 2202;
pub const RAW_UHDM_LET_DECL: u32 = 2203;
pub const RAW_UHDM_LET_DECLS: u32 = 2204;
pub const RAW_UHDM_LET_EXPR: u32 = 2205;
pub const RAW_UHDM_LHS: u32 = 2206;
pub const RAW_UHDM_LOADS: u32 = 2207;
pub const RAW_UHDM_LOCAL_DRIVERS: u32 = 2208;
pub const RAW_UHDM_LOCAL_LOADS: u32 = 2209;
pub const RAW_UHDM_LOGIC_NET: u32 = 2210;
pub const RAW_UHDM_LOGIC_TYPESPEC: u32 = 2211;
pub const RAW_UHDM_LOGIC_VAR: u32 = 2212;
pub const RAW_UHDM_LOGIC_VARS: u32 = 2213;
pub const RAW_UHDM_LONG_INT_TYPESPEC: u32 = 2214;
pub const RAW_UHDM_LONG_INT_VAR: u32 = 2215;
pub const RAW_UHDM_LOW_CONN: u32 = 2216;
pub const RAW_UHDM_MEMBERS: u32 = 2217;
pub const RAW_UHDM_MESSAGES: u32 = 2218;
pub const RAW_UHDM_METHOD_FUNC_CALL: u32 = 2219;
pub const RAW_UHDM_METHOD_FUNC_TASK_CALL_GROUP: u32 = 2220;
pub const RAW_UHDM_METHOD_TASK_CALL: u32 = 2221;
pub const RAW_UHDM_MOD_PATH: u32 = 2222;
pub const RAW_UHDM_MOD_PATHS: u32 = 2223;
pub const RAW_UHDM_MODPORT: u32 = 2224;
pub const RAW_UHDM_MODPORTS: u32 = 2225;
pub const RAW_UHDM_MODULE_ARRAY: u32 = 2226;
pub const RAW_UHDM_MODULE_ARRAYS: u32 = 2227;
pub const RAW_UHDM_MODULE_INST: u32 = 2228;
pub const RAW_UHDM_MODULE_TYPESPEC: u32 = 2229;
pub const RAW_UHDM_MODULES: u32 = 2230;
pub const RAW_UHDM_MULTICLOCK_SEQUENCE_EXPR: u32 = 2231;
pub const RAW_UHDM_NAMED_BEGIN: u32 = 2232;
pub const RAW_UHDM_NAMED_EVENT: u32 = 2233;
pub const RAW_UHDM_NAMED_EVENT_ARRAY: u32 = 2234;
pub const RAW_UHDM_NAMED_EVENT_ARRAYS: u32 = 2235;
pub const RAW_UHDM_NAMED_EVENT_SEQUENCE_EXPR_GROUP: u32 = 2236;
pub const RAW_UHDM_NAMED_EVENT_SEQUENCE_EXPR_GROUPS: u32 = 2237;
pub const RAW_UHDM_NAMED_EVENTS: u32 = 2238;
pub const RAW_UHDM_NAMED_FORK: u32 = 2239;
pub const RAW_UHDM_NET: u32 = 2240;
pub const RAW_UHDM_NET_BIT: u32 = 2241;
pub const RAW_UHDM_NET_BITS: u32 = 2242;
pub const RAW_UHDM_NET_DRIVERS: u32 = 2243;
pub const RAW_UHDM_NET_LOADS: u32 = 2244;
pub const RAW_UHDM_NETS: u32 = 2245;
pub const RAW_UHDM_NETS_VARS_REF_OBJ_GROUP: u32 = 2246;
pub const RAW_UHDM_NULL_STMT: u32 = 2247;
pub const RAW_UHDM_OPERAND_GROUP: u32 = 2248;
pub const RAW_UHDM_OPERANDS: u32 = 2249;
pub const RAW_UHDM_OPERATION: u32 = 2250;
pub const RAW_UHDM_ORDERED_WAIT: u32 = 2251;
pub const RAW_UHDM_OUTPUT_SKEW: u32 = 2252;
pub const RAW_UHDM_PACKAGE: u32 = 2253;
pub const RAW_UHDM_PACKED_ARRAY_NET: u32 = 2254;
pub const RAW_UHDM_PACKED_ARRAY_TYPESPEC: u32 = 2255;
pub const RAW_UHDM_PACKED_ARRAY_VAR: u32 = 2256;
pub const RAW_UHDM_PARAM_ASSIGN: u32 = 2257;
pub const RAW_UHDM_PARAM_ASSIGNS: u32 = 2258;
pub const RAW_UHDM_PARAMETER: u32 = 2259;
pub const RAW_UHDM_PARAMETERS: u32 = 2260;
pub const RAW_UHDM_PART_SELECT: u32 = 2261;
pub const RAW_UHDM_PATH_ELEMS: u32 = 2262;
pub const RAW_UHDM_PATH_TERM: u32 = 2263;
pub const RAW_UHDM_PATH_TERMS: u32 = 2264;
pub const RAW_UHDM_PATTERN: u32 = 2265;
pub const RAW_UHDM_PATTERN_EXPR_GROUP: u32 = 2266;
pub const RAW_UHDM_PORT: u32 = 2267;
pub const RAW_UHDM_PORT_BIT: u32 = 2268;
pub const RAW_UHDM_PORTS: u32 = 2269;
pub const RAW_UHDM_PREFIX: u32 = 2270;
pub const RAW_UHDM_PRIM_TERM: u32 = 2271;
pub const RAW_UHDM_PRIM_TERMS: u32 = 2272;
pub const RAW_UHDM_PRIMITIVE: u32 = 2273;
pub const RAW_UHDM_PRIMITIVE_ARRAY: u32 = 2274;
pub const RAW_UHDM_PRIMITIVE_ARRAYS: u32 = 2275;
pub const RAW_UHDM_PRIMITIVES: u32 = 2276;
pub const RAW_UHDM_PROCESS: u32 = 2277;
pub const RAW_UHDM_PROCESS_STMT: u32 = 2278;
pub const RAW_UHDM_PROGRAM: u32 = 2279;
pub const RAW_UHDM_PROGRAM_ARRAY: u32 = 2280;
pub const RAW_UHDM_PROGRAM_ARRAYS: u32 = 2281;
pub const RAW_UHDM_PROGRAMS: u32 = 2282;
pub const RAW_UHDM_PROP_FORMAL_DECL: u32 = 2283;
pub const RAW_UHDM_PROP_FORMAL_DECLS: u32 = 2284;
pub const RAW_UHDM_PROPERTY: u32 = 2285;
pub const RAW_UHDM_PROPERTY_DECL: u32 = 2286;
pub const RAW_UHDM_PROPERTY_DECLS: u32 = 2287;
pub const RAW_UHDM_PROPERTY_EXPR: u32 = 2288;
pub const RAW_UHDM_PROPERTY_EXPR_GROUP: u32 = 2289;
pub const RAW_UHDM_PROPERTY_EXPR_NAMED_EVENT_GROUP: u32 = 2290;
pub const RAW_UHDM_PROPERTY_INST: u32 = 2291;
pub const RAW_UHDM_PROPERTY_INST_SPEC_GROUP: u32 = 2292;
pub const RAW_UHDM_PROPERTY_SPEC: u32 = 2293;
pub const RAW_UHDM_PROPERTY_TYPESPEC: u32 = 2294;
pub const RAW_UHDM_RANGE: u32 = 2295;
pub const RAW_UHDM_RANGES: u32 = 2296;
pub const RAW_UHDM_REAL_TYPESPEC: u32 = 2297;
pub const RAW_UHDM_REAL_VAR: u32 = 2298;
pub const RAW_UHDM_REF_MODULE: u32 = 2299;
pub const RAW_UHDM_REF_MODULES: u32 = 2300;
pub const RAW_UHDM_REF_OBJ: u32 = 2301;
pub const RAW_UHDM_REF_OBJ_INTERF_NET_VAR_GROUP: u32 = 2302;
pub const RAW_UHDM_REF_TYPESPEC: u32 = 2303;
pub const RAW_UHDM_REF_VAR: u32 = 2304;
pub const RAW_UHDM_REG: u32 = 2305;
pub const RAW_UHDM_REG_ARRAY: u32 = 2306;
pub const RAW_UHDM_REGS: u32 = 2307;
pub const RAW_UHDM_RELEASE: u32 = 2308;
pub const RAW_UHDM_REPEAT: u32 = 2309;
pub const RAW_UHDM_REPEAT_CONTROL: u32 = 2310;
pub const RAW_UHDM_RESOLUTION_FUNC: u32 = 2311;
pub const RAW_UHDM_RESTRICT: u32 = 2312;
pub const RAW_UHDM_RETURN: u32 = 2313;
pub const RAW_UHDM_RETURN_STMT: u32 = 2314;
pub const RAW_UHDM_RHS: u32 = 2315;
pub const RAW_UHDM_RIGHT_EXPR: u32 = 2316;
pub const RAW_UHDM_RIGHT_RANGE: u32 = 2317;
pub const RAW_UHDM_ROOT_VALUE: u32 = 2318;
pub const RAW_UHDM_SCOPE: u32 = 2319;
pub const RAW_UHDM_SCOPES: u32 = 2320;
pub const RAW_UHDM_SEQ_FORMAL_DECL: u32 = 2321;
pub const RAW_UHDM_SEQ_FORMAL_DECLS: u32 = 2322;
pub const RAW_UHDM_SEQUENCE: u32 = 2323;
pub const RAW_UHDM_SEQUENCE_DECL: u32 = 2324;
pub const RAW_UHDM_SEQUENCE_DECLS: u32 = 2325;
pub const RAW_UHDM_SEQUENCE_EXPR_GROUP: u32 = 2326;
pub const RAW_UHDM_SEQUENCE_EXPR_MULTICLOCK_GROUP: u32 = 2327;
pub const RAW_UHDM_SEQUENCE_INST: u32 = 2328;
pub const RAW_UHDM_SEQUENCE_TYPESPEC: u32 = 2329;
pub const RAW_UHDM_SHORT_INT_TYPESPEC: u32 = 2330;
pub const RAW_UHDM_SHORT_INT_VAR: u32 = 2331;
pub const RAW_UHDM_SHORT_REAL_TYPESPEC: u32 = 2332;
pub const RAW_UHDM_SHORT_REAL_VAR: u32 = 2333;
pub const RAW_UHDM_SIM_NET: u32 = 2334;
pub const RAW_UHDM_SIMPLE_EXPR: u32 = 2335;
pub const RAW_UHDM_SIMPLE_EXPR_USE_GROUP: u32 = 2336;
pub const RAW_UHDM_SOFT_DISABLE: u32 = 2337;
pub const RAW_UHDM_SOLVE_AFTERS: u32 = 2338;
pub const RAW_UHDM_SOLVE_BEFORES: u32 = 2339;
pub const RAW_UHDM_SPEC_PARAM: u32 = 2340;
pub const RAW_UHDM_SPEC_PARAMS: u32 = 2341;
pub const RAW_UHDM_STMT: u32 = 2342;
pub const RAW_UHDM_STMTS: u32 = 2343;
pub const RAW_UHDM_STRING_TYPESPEC: u32 = 2344;
pub const RAW_UHDM_STRING_VAR: u32 = 2345;
pub const RAW_UHDM_STRUCT_NET: u32 = 2346;
pub const RAW_UHDM_STRUCT_PATTERN: u32 = 2347;
pub const RAW_UHDM_STRUCT_TYPESPEC: u32 = 2348;
pub const RAW_UHDM_STRUCT_VAR: u32 = 2349;
pub const RAW_UHDM_SWITCH_ARRAY: u32 = 2350;
pub const RAW_UHDM_SWITCH_TRAN: u32 = 2351;
pub const RAW_UHDM_SYS_FUNC_CALL: u32 = 2352;
pub const RAW_UHDM_SYS_FUNC_TASK_CALL_GROUP: u32 = 2353;
pub const RAW_UHDM_SYS_TASK_CALL: u32 = 2354;
pub const RAW_UHDM_TABLE_ENTRY: u32 = 2355;
pub const RAW_UHDM_TABLE_ENTRYS: u32 = 2356;
pub const RAW_UHDM_TAGGED_PATTERN: u32 = 2357;
pub const RAW_UHDM_TASK: u32 = 2358;
pub const RAW_UHDM_TASK_CALL: u32 = 2359;
pub const RAW_UHDM_TASK_FUNC: u32 = 2360;
pub const RAW_UHDM_TASK_FUNC_NAMED_BEGIN_FORK_GROUP: u32 = 2361;
pub const RAW_UHDM_TASK_FUNCS: u32 = 2362;
pub const RAW_UHDM_TASKS: u32 = 2363;
pub const RAW_UHDM_TCHK: u32 = 2364;
pub const RAW_UHDM_TCHK_DATA_TERM: u32 = 2365;
pub const RAW_UHDM_TCHK_REF_TERM: u32 = 2366;
pub const RAW_UHDM_TCHK_TERM: u32 = 2367;
pub const RAW_UHDM_TCHK_TERMS: u32 = 2368;
pub const RAW_UHDM_TCHKS: u32 = 2369;
pub const RAW_UHDM_TF_CALL: u32 = 2370;
pub const RAW_UHDM_TF_CALL_ARGS: u32 = 2371;
pub const RAW_UHDM_THREAD_OBJ: u32 = 2372;
pub const RAW_UHDM_THREADS: u32 = 2373;
pub const RAW_UHDM_TIME_NET: u32 = 2374;
pub const RAW_UHDM_TIME_TYPESPEC: u32 = 2375;
pub const RAW_UHDM_TIME_VAR: u32 = 2376;
pub const RAW_UHDM_TYPE_PARAMETER: u32 = 2379;
pub const RAW_UHDM_TYPEDEF_ALIAS: u32 = 2380;
pub const RAW_UHDM_TYPESPEC: u32 = 2381;
pub const RAW_UHDM_TYPESPEC_MEMBER: u32 = 2382;
pub const RAW_UHDM_TYPESPECS: u32 = 2383;
pub const RAW_UHDM_UDP: u32 = 2384;
pub const RAW_UHDM_UDP_ARRAY: u32 = 2385;
pub const RAW_UHDM_UDP_DEFN: u32 = 2386;
pub const RAW_UHDM_UNION_TYPESPEC: u32 = 2387;
pub const RAW_UHDM_UNION_VAR: u32 = 2388;
pub const RAW_UHDM_UNSUPPORTED_EXPR: u32 = 2389;
pub const RAW_UHDM_UNSUPPORTED_STMT: u32 = 2390;
pub const RAW_UHDM_UNSUPPORTED_TYPESPEC: u32 = 2391;
pub const RAW_UHDM_USER_SYSTF: u32 = 2392;
pub const RAW_UHDM_VALUE_RANGE: u32 = 2393;
pub const RAW_UHDM_VAR_BIT: u32 = 2394;
pub const RAW_UHDM_VAR_BITS: u32 = 2395;
pub const RAW_UHDM_VAR_SELECT: u32 = 2396;
pub const RAW_UHDM_VAR_SELECTS: u32 = 2397;
pub const RAW_UHDM_VARIABLE: u32 = 2398;
pub const RAW_UHDM_VARIABLE_DRIVERS: u32 = 2399;
pub const RAW_UHDM_VARIABLE_DRIVERS_GROUP: u32 = 2400;
pub const RAW_UHDM_VARIABLE_LOADS: u32 = 2401;
pub const RAW_UHDM_VARIABLE_LOADS_GROUP: u32 = 2402;
pub const RAW_UHDM_VARIABLES: u32 = 2403;
pub const RAW_UHDM_VARIABLES_OPERATION_GROUP: u32 = 2404;
pub const RAW_UHDM_VIRTUAL_INTERFACE_VAR: u32 = 2405;
pub const RAW_UHDM_VIRTUAL_INTERFACE_VARS: u32 = 2406;
pub const RAW_UHDM_VOID_TYPESPEC: u32 = 2407;
pub const RAW_UHDM_WAIT_FORK: u32 = 2428;
pub const RAW_UHDM_WAIT_STMT: u32 = 2429;
pub const RAW_UHDM_WAITS: u32 = 2430;
pub const RAW_UHDM_WEIGHT: u32 = 2431;
pub const RAW_UHDM_WHILE_STMT: u32 = 2432;
pub const RAW_UHDM_WIDTH_EXPR: u32 = 2433;
pub const RAW_UHDM_WITH: u32 = 2434;

pub fn raw_type_name(type_id: u32) -> &'static str {
    match type_id {
        RAW_UHDM_ACTUAL => "uhdmactual",
        RAW_UHDM_ACTUAL_GROUP => "uhdmactual_group",
        RAW_UHDM_ACTUAL_TYPESPEC => "uhdmactual_typespec",
        RAW_UHDM_ALIAS_STMT => "uhdmalias_stmt",
        RAW_UHDM_ALIAS_STMTS => "uhdmalias_stmts",
        RAW_UHDM_ALWAYS => "uhdmalways",
        RAW_UHDM_ANY_PATTERN => "uhdmany_pattern",
        RAW_UHDM_ARGUMENTS => "uhdmarguments",
        RAW_UHDM_ARRAY_EXPR => "uhdmarray_expr",
        RAW_UHDM_ARRAY_NET => "uhdmarray_net",
        RAW_UHDM_ARRAY_NETS => "uhdmarray_nets",
        RAW_UHDM_ARRAY_TYPESPEC => "uhdmarray_typespec",
        RAW_UHDM_ARRAY_VAR => "uhdmarray_var",
        RAW_UHDM_ARRAY_VAR_MEMS => "uhdmarray_var_mems",
        RAW_UHDM_ARRAY_VARS => "uhdmarray_vars",
        RAW_UHDM_ASSERT_STMT => "uhdmassert_stmt",
        RAW_UHDM_ASSERTION => "uhdmassertion",
        RAW_UHDM_ASSERTIONS => "uhdmassertions",
        RAW_UHDM_ASSIGN_STMT => "uhdmassign_stmt",
        RAW_UHDM_ASSIGNMENT => "uhdmassignment",
        RAW_UHDM_ASSUME => "uhdmassume",
        RAW_UHDM_ATOMIC_STMT => "uhdmatomic_stmt",
        RAW_UHDM_ATTRIBUTE => "uhdmattribute",
        RAW_UHDM_ATTRIBUTES => "uhdmattributes",
        RAW_UHDM_BASE_EXPR => "uhdmbase_expr",
        RAW_UHDM_BASE_TYPESPEC => "uhdmbase_typespec",
        RAW_UHDM_BEGIN => "uhdmbegin",
        RAW_UHDM_BIT_SELECT => "uhdmbit_select",
        RAW_UHDM_BIT_TYPESPEC => "uhdmbit_typespec",
        RAW_UHDM_BIT_VAR => "uhdmbit_var",
        RAW_UHDM_BITS => "uhdmbits",
        RAW_UHDM_BREAK_STMT => "uhdmbreak_stmt",
        RAW_UHDM_BYTE_TYPESPEC => "uhdmbyte_typespec",
        RAW_UHDM_BYTE_VAR => "uhdmbyte_var",
        RAW_UHDM_CASE_ITEM => "uhdmcase_item",
        RAW_UHDM_CASE_ITEMS => "uhdmcase_items",
        RAW_UHDM_CASE_PROPERTY => "uhdmcase_property",
        RAW_UHDM_CASE_PROPERTY_ITEM => "uhdmcase_property_item",
        RAW_UHDM_CASE_PROPERTY_ITEMS => "uhdmcase_property_items",
        RAW_UHDM_CASE_STMT => "uhdmcase_stmt",
        RAW_UHDM_CAST_TO_EXPR => "uhdmcast_to_expr",
        RAW_UHDM_CHANDLE_TYPESPEC => "uhdmchandle_typespec",
        RAW_UHDM_CHANDLE_VAR => "uhdmchandle_var",
        RAW_UHDM_CHECKER_DECL => "uhdmchecker_decl",
        RAW_UHDM_CHECKER_INST => "uhdmchecker_inst",
        RAW_UHDM_CHECKER_INST_PORT => "uhdmchecker_inst_port",
        RAW_UHDM_CHECKER_PORT => "uhdmchecker_port",
        RAW_UHDM_CLASS_DEFN => "uhdmclass_defn",
        RAW_UHDM_CLASS_DEFNS => "uhdmclass_defns",
        RAW_UHDM_CLASS_OBJ => "uhdmclass_obj",
        RAW_UHDM_CLASS_TYPESPEC => "uhdmclass_typespec",
        RAW_UHDM_CLASS_TYPESPECS => "uhdmclass_typespecs",
        RAW_UHDM_CLASS_VAR => "uhdmclass_var",
        RAW_UHDM_CLOCKED_PROPERTY => "uhdmclocked_property",
        RAW_UHDM_CLOCKED_SEQ => "uhdmclocked_seq",
        RAW_UHDM_CLOCKED_SEQS => "uhdmclocked_seqs",
        RAW_UHDM_CLOCKING_BLOCK => "uhdmclocking_block",
        RAW_UHDM_CLOCKING_BLOCKS => "uhdmclocking_blocks",
        RAW_UHDM_CLOCKING_EVENT => "uhdmclocking_event",
        RAW_UHDM_CLOCKING_IO_DECL => "uhdmclocking_io_decl",
        RAW_UHDM_CLOCKING_IO_DECLS => "uhdmclocking_io_decls",
        RAW_UHDM_CONCURRENT_ASSERTIONS => "uhdmconcurrent_assertions",
        RAW_UHDM_CONDITION => "uhdmcondition",
        RAW_UHDM_CONSTANT => "uhdmconstant",
        RAW_UHDM_CONSTR_FOREACH => "uhdmconstr_foreach",
        RAW_UHDM_CONSTR_IF => "uhdmconstr_if",
        RAW_UHDM_CONSTR_IF_ELSE => "uhdmconstr_if_else",
        RAW_UHDM_CONSTRAINT => "uhdmconstraint",
        RAW_UHDM_CONSTRAINT_EXPR => "uhdmconstraint_expr",
        RAW_UHDM_CONSTRAINT_EXPRS => "uhdmconstraint_exprs",
        RAW_UHDM_CONSTRAINT_ITEM_GROUP => "uhdmconstraint_item_group",
        RAW_UHDM_CONSTRAINT_ITEMS => "uhdmconstraint_items",
        RAW_UHDM_CONSTRAINT_ORDERING => "uhdmconstraint_ordering",
        RAW_UHDM_CONSTRAINTS => "uhdmconstraints",
        RAW_UHDM_CONT_ASSIGN => "uhdmcont_assign",
        RAW_UHDM_CONT_ASSIGN_BIT => "uhdmcont_assign_bit",
        RAW_UHDM_CONT_ASSIGN_BITS => "uhdmcont_assign_bits",
        RAW_UHDM_CONT_ASSIGNS => "uhdmcont_assigns",
        RAW_UHDM_CONTINUE_STMT => "uhdmcontinue_stmt",
        RAW_UHDM_COVER => "uhdmcover",
        RAW_UHDM_DEASSIGN => "uhdmdeassign",
        RAW_UHDM_DEF_PARAM => "uhdmdef_param",
        RAW_UHDM_DEF_PARAMS => "uhdmdef_params",
        RAW_UHDM_DEFAULT_CLOCKING => "uhdmdefault_clocking",
        RAW_UHDM_DEFAULT_VALUE => "uhdmdefault_value",
        RAW_UHDM_DELAY => "uhdmdelay",
        RAW_UHDM_DELAY_CONTROL => "uhdmdelay_control",
        RAW_UHDM_DELAY_TERM => "uhdmdelay_term",
        RAW_UHDM_DERIVEDS => "uhdmderiveds",
        RAW_UHDM_DESIGN => "uhdmdesign",
        RAW_UHDM_DISABLE => "uhdmdisable",
        RAW_UHDM_DISABLE_FORK => "uhdmdisable_fork",
        RAW_UHDM_DISABLES => "uhdmdisables",
        RAW_UHDM_DIST_ITEM => "uhdmdist_item",
        RAW_UHDM_DIST_ITEMS => "uhdmdist_items",
        RAW_UHDM_DISTRIBUTION => "uhdmdistribution",
        RAW_UHDM_DO_WHILE => "uhdmdo_while",
        RAW_UHDM_DRIVERS => "uhdmdrivers",
        RAW_UHDM_ELAB_TASKS => "uhdmelab_tasks",
        RAW_UHDM_ELEM_TYPESPEC => "uhdmelem_typespec",
        RAW_UHDM_ELEMENTS => "uhdmelements",
        RAW_UHDM_ELSE_CONSTRAINT_EXPRS => "uhdmelse_constraint_exprs",
        RAW_UHDM_ELSE_STMT => "uhdmelse_stmt",
        RAW_UHDM_ENUM_CONST => "uhdmenum_const",
        RAW_UHDM_ENUM_CONSTS => "uhdmenum_consts",
        RAW_UHDM_ENUM_NET => "uhdmenum_net",
        RAW_UHDM_ENUM_STRUCT_PACKED_NET_GROUP => "uhdmenum_struct_packed_net_group",
        RAW_UHDM_ENUM_STRUCT_UNION_PACKED_ARRAY_TYPESPEC_GROUP => "uhdmenum_struct_union_packed_array_typespec_group",
        RAW_UHDM_ENUM_STRUCT_UNION_PACKED_VAR_GROUP => "uhdmenum_struct_union_packed_var_group",
        RAW_UHDM_ENUM_TYPESPEC => "uhdmenum_typespec",
        RAW_UHDM_ENUM_VAR => "uhdmenum_var",
        RAW_UHDM_EVENT_CONTROL => "uhdmevent_control",
        RAW_UHDM_EVENT_STMT => "uhdmevent_stmt",
        RAW_UHDM_EVENT_TYPESPEC => "uhdmevent_typespec",
        RAW_UHDM_EXPECT_STMT => "uhdmexpect_stmt",
        RAW_UHDM_EXPR => "uhdmexpr",
        RAW_UHDM_EXPR_CONSTR_GROUP => "uhdmexpr_constr_group",
        RAW_UHDM_EXPR_DIST => "uhdmexpr_dist",
        RAW_UHDM_EXPR_INDEX => "uhdmexpr_index",
        RAW_UHDM_EXPR_INDEXES => "uhdmexpr_indexes",
        RAW_UHDM_EXPR_INTERF_EXPR_GROUP => "uhdmexpr_interf_expr_group",
        RAW_UHDM_EXPR_RANGE_GROUP => "uhdmexpr_range_group",
        RAW_UHDM_EXPR_REF_OBJ_GROUP => "uhdmexpr_ref_obj_group",
        RAW_UHDM_EXPR_SEQUENCE_INST_GROUP => "uhdmexpr_sequence_inst_group",
        RAW_UHDM_EXPR_SEQUENCE_INST_NAMED_EVENT_GROUP => "uhdmexpr_sequence_inst_named_event_group",
        RAW_UHDM_EXPR_TCHK_TERM_GROUP => "uhdmexpr_tchk_term_group",
        RAW_UHDM_EXPR_TCHK_TERMS => "uhdmexpr_tchk_terms",
        RAW_UHDM_EXPR_TYPESPEC_GROUP => "uhdmexpr_typespec_group",
        RAW_UHDM_EXPRESSIONS => "uhdmexpressions",
        RAW_UHDM_EXPRS => "uhdmexprs",
        RAW_UHDM_EXTENDS => "uhdmextends",
        RAW_UHDM_FINAL_STMT => "uhdmfinal_stmt",
        RAW_UHDM_FOR_STMT => "uhdmfor_stmt",
        RAW_UHDM_FORCE => "uhdmforce",
        RAW_UHDM_FOREACH_STMT => "uhdmforeach_stmt",
        RAW_UHDM_FOREVER_STMT => "uhdmforever_stmt",
        RAW_UHDM_FORK_STMT => "uhdmfork_stmt",
        RAW_UHDM_FUNC_CALL => "uhdmfunc_call",
        RAW_UHDM_FUNCTION => "uhdmfunction",
        RAW_UHDM_FUNCTIONS => "uhdmfunctions",
        RAW_UHDM_GATE => "uhdmgate",
        RAW_UHDM_GATE_ARRAY => "uhdmgate_array",
        RAW_UHDM_GEN_CASE => "uhdmgen_case",
        RAW_UHDM_GEN_FOR => "uhdmgen_for",
        RAW_UHDM_GEN_IF => "uhdmgen_if",
        RAW_UHDM_GEN_IF_ELSE => "uhdmgen_if_else",
        RAW_UHDM_GEN_REGION => "uhdmgen_region",
        RAW_UHDM_GEN_SCOPE => "uhdmgen_scope",
        RAW_UHDM_GEN_SCOPE_ARRAY => "uhdmgen_scope_array",
        RAW_UHDM_GEN_SCOPE_ARRAYS => "uhdmgen_scope_arrays",
        RAW_UHDM_GEN_SCOPES => "uhdmgen_scopes",
        RAW_UHDM_GEN_STMT => "uhdmgen_stmt",
        RAW_UHDM_GEN_STMTS => "uhdmgen_stmts",
        RAW_UHDM_GEN_VAR => "uhdmgen_var",
        RAW_UHDM_GLOBAL_CLOCKING => "uhdmglobal_clocking",
        RAW_UHDM_HIER_PATH => "uhdmhier_path",
        RAW_UHDM_HIGH_CONN => "uhdmhigh_conn",
        RAW_UHDM_IF_ELSE => "uhdmif_else",
        RAW_UHDM_IF_STMT => "uhdmif_stmt",
        RAW_UHDM_IMMEDIATE_ASSERT => "uhdmimmediate_assert",
        RAW_UHDM_IMMEDIATE_ASSUME => "uhdmimmediate_assume",
        RAW_UHDM_IMMEDIATE_COVER => "uhdmimmediate_cover",
        RAW_UHDM_IMPLICATION => "uhdmimplication",
        RAW_UHDM_IMPORT_TYPESPEC => "uhdmimport_typespec",
        RAW_UHDM_INCLUDE_FILE_INFO => "uhdminclude_file_info",
        RAW_UHDM_INCLUDE_FILE_INFOS => "uhdminclude_file_infos",
        RAW_UHDM_INDEX => "uhdmindex",
        RAW_UHDM_INDEX_TYPESPEC => "uhdmindex_typespec",
        RAW_UHDM_INDEXED_PART_SELECT => "uhdmindexed_part_select",
        RAW_UHDM_INDEXES => "uhdmindexes",
        RAW_UHDM_INITIAL => "uhdminitial",
        RAW_UHDM_INPUT_SKEW => "uhdminput_skew",
        RAW_UHDM_INSTANCE => "uhdminstance",
        RAW_UHDM_INSTANCE_ARRAY => "uhdminstance_array",
        RAW_UHDM_INSTANCE_ITEM => "uhdminstance_item",
        RAW_UHDM_INSTANCE_ITEMS => "uhdminstance_items",
        RAW_UHDM_INSTANCES => "uhdminstances",
        RAW_UHDM_INT_TYPESPEC => "uhdmint_typespec",
        RAW_UHDM_INT_VAR => "uhdmint_var",
        RAW_UHDM_INTEGER_NET => "uhdminteger_net",
        RAW_UHDM_INTEGER_TYPESPEC => "uhdminteger_typespec",
        RAW_UHDM_INTEGER_VAR => "uhdminteger_var",
        RAW_UHDM_INTERF_PROG_MOD_GROUP => "uhdminterf_prog_mod_group",
        RAW_UHDM_INTERFACE_ARRAY => "uhdminterface_array",
        RAW_UHDM_INTERFACE_ARRAYS => "uhdminterface_arrays",
        RAW_UHDM_INTERFACE_EXPR => "uhdminterface_expr",
        RAW_UHDM_INTERFACE_INST => "uhdminterface_inst",
        RAW_UHDM_INTERFACE_TF_DECL => "uhdminterface_tf_decl",
        RAW_UHDM_INTERFACE_TF_DECLS => "uhdminterface_tf_decls",
        RAW_UHDM_INTERFACE_TYPESPEC => "uhdminterface_typespec",
        RAW_UHDM_INTERFACES => "uhdminterfaces",
        RAW_UHDM_IO_DECL => "uhdmio_decl",
        RAW_UHDM_IO_DECLS => "uhdmio_decls",
        RAW_UHDM_ITEM => "uhdmitem",
        RAW_UHDM_LEFT_EXPR => "uhdmleft_expr",
        RAW_UHDM_LEFT_RANGE => "uhdmleft_range",
        RAW_UHDM_LET_DECL => "uhdmlet_decl",
        RAW_UHDM_LET_DECLS => "uhdmlet_decls",
        RAW_UHDM_LET_EXPR => "uhdmlet_expr",
        RAW_UHDM_LHS => "uhdmlhs",
        RAW_UHDM_LOADS => "uhdmloads",
        RAW_UHDM_LOCAL_DRIVERS => "uhdmlocal_drivers",
        RAW_UHDM_LOCAL_LOADS => "uhdmlocal_loads",
        RAW_UHDM_LOGIC_NET => "uhdmlogic_net",
        RAW_UHDM_LOGIC_TYPESPEC => "uhdmlogic_typespec",
        RAW_UHDM_LOGIC_VAR => "uhdmlogic_var",
        RAW_UHDM_LOGIC_VARS => "uhdmlogic_vars",
        RAW_UHDM_LONG_INT_TYPESPEC => "uhdmlong_int_typespec",
        RAW_UHDM_LONG_INT_VAR => "uhdmlong_int_var",
        RAW_UHDM_LOW_CONN => "uhdmlow_conn",
        RAW_UHDM_MEMBERS => "uhdmmembers",
        RAW_UHDM_MESSAGES => "uhdmmessages",
        RAW_UHDM_METHOD_FUNC_CALL => "uhdmmethod_func_call",
        RAW_UHDM_METHOD_FUNC_TASK_CALL_GROUP => "uhdmmethod_func_task_call_group",
        RAW_UHDM_METHOD_TASK_CALL => "uhdmmethod_task_call",
        RAW_UHDM_MOD_PATH => "uhdmmod_path",
        RAW_UHDM_MOD_PATHS => "uhdmmod_paths",
        RAW_UHDM_MODPORT => "uhdmmodport",
        RAW_UHDM_MODPORTS => "uhdmmodports",
        RAW_UHDM_MODULE_ARRAY => "uhdmmodule_array",
        RAW_UHDM_MODULE_ARRAYS => "uhdmmodule_arrays",
        RAW_UHDM_MODULE_INST => "uhdmmodule_inst",
        RAW_UHDM_MODULE_TYPESPEC => "uhdmmodule_typespec",
        RAW_UHDM_MODULES => "uhdmmodules",
        RAW_UHDM_MULTICLOCK_SEQUENCE_EXPR => "uhdmmulticlock_sequence_expr",
        RAW_UHDM_NAMED_BEGIN => "uhdmnamed_begin",
        RAW_UHDM_NAMED_EVENT => "uhdmnamed_event",
        RAW_UHDM_NAMED_EVENT_ARRAY => "uhdmnamed_event_array",
        RAW_UHDM_NAMED_EVENT_ARRAYS => "uhdmnamed_event_arrays",
        RAW_UHDM_NAMED_EVENT_SEQUENCE_EXPR_GROUP => "uhdmnamed_event_sequence_expr_group",
        RAW_UHDM_NAMED_EVENT_SEQUENCE_EXPR_GROUPS => "uhdmnamed_event_sequence_expr_groups",
        RAW_UHDM_NAMED_EVENTS => "uhdmnamed_events",
        RAW_UHDM_NAMED_FORK => "uhdmnamed_fork",
        RAW_UHDM_NET => "uhdmnet",
        RAW_UHDM_NET_BIT => "uhdmnet_bit",
        RAW_UHDM_NET_BITS => "uhdmnet_bits",
        RAW_UHDM_NET_DRIVERS => "uhdmnet_drivers",
        RAW_UHDM_NET_LOADS => "uhdmnet_loads",
        RAW_UHDM_NETS => "uhdmnets",
        RAW_UHDM_NETS_VARS_REF_OBJ_GROUP => "uhdmnets_vars_ref_obj_group",
        RAW_UHDM_NULL_STMT => "uhdmnull_stmt",
        RAW_UHDM_OPERAND_GROUP => "uhdmoperand_group",
        RAW_UHDM_OPERANDS => "uhdmoperands",
        RAW_UHDM_OPERATION => "uhdmoperation",
        RAW_UHDM_ORDERED_WAIT => "uhdmordered_wait",
        RAW_UHDM_OUTPUT_SKEW => "uhdmoutput_skew",
        RAW_UHDM_PACKAGE => "uhdmpackage",
        RAW_UHDM_PACKED_ARRAY_NET => "uhdmpacked_array_net",
        RAW_UHDM_PACKED_ARRAY_TYPESPEC => "uhdmpacked_array_typespec",
        RAW_UHDM_PACKED_ARRAY_VAR => "uhdmpacked_array_var",
        RAW_UHDM_PARAM_ASSIGN => "uhdmparam_assign",
        RAW_UHDM_PARAM_ASSIGNS => "uhdmparam_assigns",
        RAW_UHDM_PARAMETER => "uhdmparameter",
        RAW_UHDM_PARAMETERS => "uhdmparameters",
        RAW_UHDM_PART_SELECT => "uhdmpart_select",
        RAW_UHDM_PATH_ELEMS => "uhdmpath_elems",
        RAW_UHDM_PATH_TERM => "uhdmpath_term",
        RAW_UHDM_PATH_TERMS => "uhdmpath_terms",
        RAW_UHDM_PATTERN => "uhdmpattern",
        RAW_UHDM_PATTERN_EXPR_GROUP => "uhdmpattern_expr_group",
        RAW_UHDM_PORT => "uhdmport",
        RAW_UHDM_PORT_BIT => "uhdmport_bit",
        RAW_UHDM_PORTS => "uhdmports",
        RAW_UHDM_PREFIX => "uhdmprefix",
        RAW_UHDM_PRIM_TERM => "uhdmprim_term",
        RAW_UHDM_PRIM_TERMS => "uhdmprim_terms",
        RAW_UHDM_PRIMITIVE => "uhdmprimitive",
        RAW_UHDM_PRIMITIVE_ARRAY => "uhdmprimitive_array",
        RAW_UHDM_PRIMITIVE_ARRAYS => "uhdmprimitive_arrays",
        RAW_UHDM_PRIMITIVES => "uhdmprimitives",
        RAW_UHDM_PROCESS => "uhdmprocess",
        RAW_UHDM_PROCESS_STMT => "uhdmprocess_stmt",
        RAW_UHDM_PROGRAM => "uhdmprogram",
        RAW_UHDM_PROGRAM_ARRAY => "uhdmprogram_array",
        RAW_UHDM_PROGRAM_ARRAYS => "uhdmprogram_arrays",
        RAW_UHDM_PROGRAMS => "uhdmprograms",
        RAW_UHDM_PROP_FORMAL_DECL => "uhdmprop_formal_decl",
        RAW_UHDM_PROP_FORMAL_DECLS => "uhdmprop_formal_decls",
        RAW_UHDM_PROPERTY => "uhdmproperty",
        RAW_UHDM_PROPERTY_DECL => "uhdmproperty_decl",
        RAW_UHDM_PROPERTY_DECLS => "uhdmproperty_decls",
        RAW_UHDM_PROPERTY_EXPR => "uhdmproperty_expr",
        RAW_UHDM_PROPERTY_EXPR_GROUP => "uhdmproperty_expr_group",
        RAW_UHDM_PROPERTY_EXPR_NAMED_EVENT_GROUP => "uhdmproperty_expr_named_event_group",
        RAW_UHDM_PROPERTY_INST => "uhdmproperty_inst",
        RAW_UHDM_PROPERTY_INST_SPEC_GROUP => "uhdmproperty_inst_spec_group",
        RAW_UHDM_PROPERTY_SPEC => "uhdmproperty_spec",
        RAW_UHDM_PROPERTY_TYPESPEC => "uhdmproperty_typespec",
        RAW_UHDM_RANGE => "uhdmrange",
        RAW_UHDM_RANGES => "uhdmranges",
        RAW_UHDM_REAL_TYPESPEC => "uhdmreal_typespec",
        RAW_UHDM_REAL_VAR => "uhdmreal_var",
        RAW_UHDM_REF_MODULE => "uhdmref_module",
        RAW_UHDM_REF_MODULES => "uhdmref_modules",
        RAW_UHDM_REF_OBJ => "uhdmref_obj",
        RAW_UHDM_REF_OBJ_INTERF_NET_VAR_GROUP => "uhdmref_obj_interf_net_var_group",
        RAW_UHDM_REF_TYPESPEC => "uhdmref_typespec",
        RAW_UHDM_REF_VAR => "uhdmref_var",
        RAW_UHDM_REG => "uhdmreg",
        RAW_UHDM_REG_ARRAY => "uhdmreg_array",
        RAW_UHDM_REGS => "uhdmregs",
        RAW_UHDM_RELEASE => "uhdmrelease",
        RAW_UHDM_REPEAT => "uhdmrepeat",
        RAW_UHDM_REPEAT_CONTROL => "uhdmrepeat_control",
        RAW_UHDM_RESOLUTION_FUNC => "uhdmresolution_func",
        RAW_UHDM_RESTRICT => "uhdmrestrict",
        RAW_UHDM_RETURN => "uhdmreturn",
        RAW_UHDM_RETURN_STMT => "uhdmreturn_stmt",
        RAW_UHDM_RHS => "uhdmrhs",
        RAW_UHDM_RIGHT_EXPR => "uhdmright_expr",
        RAW_UHDM_RIGHT_RANGE => "uhdmright_range",
        RAW_UHDM_ROOT_VALUE => "uhdmroot_value",
        RAW_UHDM_SCOPE => "uhdmscope",
        RAW_UHDM_SCOPES => "uhdmscopes",
        RAW_UHDM_SEQ_FORMAL_DECL => "uhdmseq_formal_decl",
        RAW_UHDM_SEQ_FORMAL_DECLS => "uhdmseq_formal_decls",
        RAW_UHDM_SEQUENCE => "uhdmsequence",
        RAW_UHDM_SEQUENCE_DECL => "uhdmsequence_decl",
        RAW_UHDM_SEQUENCE_DECLS => "uhdmsequence_decls",
        RAW_UHDM_SEQUENCE_EXPR_GROUP => "uhdmsequence_expr_group",
        RAW_UHDM_SEQUENCE_EXPR_MULTICLOCK_GROUP => "uhdmsequence_expr_multiclock_group",
        RAW_UHDM_SEQUENCE_INST => "uhdmsequence_inst",
        RAW_UHDM_SEQUENCE_TYPESPEC => "uhdmsequence_typespec",
        RAW_UHDM_SHORT_INT_TYPESPEC => "uhdmshort_int_typespec",
        RAW_UHDM_SHORT_INT_VAR => "uhdmshort_int_var",
        RAW_UHDM_SHORT_REAL_TYPESPEC => "uhdmshort_real_typespec",
        RAW_UHDM_SHORT_REAL_VAR => "uhdmshort_real_var",
        RAW_UHDM_SIM_NET => "uhdmsim_net",
        RAW_UHDM_SIMPLE_EXPR => "uhdmsimple_expr",
        RAW_UHDM_SIMPLE_EXPR_USE_GROUP => "uhdmsimple_expr_use_group",
        RAW_UHDM_SOFT_DISABLE => "uhdmsoft_disable",
        RAW_UHDM_SOLVE_AFTERS => "uhdmsolve_afters",
        RAW_UHDM_SOLVE_BEFORES => "uhdmsolve_befores",
        RAW_UHDM_SPEC_PARAM => "uhdmspec_param",
        RAW_UHDM_SPEC_PARAMS => "uhdmspec_params",
        RAW_UHDM_STMT => "uhdmstmt",
        RAW_UHDM_STMTS => "uhdmstmts",
        RAW_UHDM_STRING_TYPESPEC => "uhdmstring_typespec",
        RAW_UHDM_STRING_VAR => "uhdmstring_var",
        RAW_UHDM_STRUCT_NET => "uhdmstruct_net",
        RAW_UHDM_STRUCT_PATTERN => "uhdmstruct_pattern",
        RAW_UHDM_STRUCT_TYPESPEC => "uhdmstruct_typespec",
        RAW_UHDM_STRUCT_VAR => "uhdmstruct_var",
        RAW_UHDM_SWITCH_ARRAY => "uhdmswitch_array",
        RAW_UHDM_SWITCH_TRAN => "uhdmswitch_tran",
        RAW_UHDM_SYS_FUNC_CALL => "uhdmsys_func_call",
        RAW_UHDM_SYS_FUNC_TASK_CALL_GROUP => "uhdmsys_func_task_call_group",
        RAW_UHDM_SYS_TASK_CALL => "uhdmsys_task_call",
        RAW_UHDM_TABLE_ENTRY => "uhdmtable_entry",
        RAW_UHDM_TABLE_ENTRYS => "uhdmtable_entrys",
        RAW_UHDM_TAGGED_PATTERN => "uhdmtagged_pattern",
        RAW_UHDM_TASK => "uhdmtask",
        RAW_UHDM_TASK_CALL => "uhdmtask_call",
        RAW_UHDM_TASK_FUNC => "uhdmtask_func",
        RAW_UHDM_TASK_FUNC_NAMED_BEGIN_FORK_GROUP => "uhdmtask_func_named_begin_fork_group",
        RAW_UHDM_TASK_FUNCS => "uhdmtask_funcs",
        RAW_UHDM_TASKS => "uhdmtasks",
        RAW_UHDM_TCHK => "uhdmtchk",
        RAW_UHDM_TCHK_DATA_TERM => "uhdmtchk_data_term",
        RAW_UHDM_TCHK_REF_TERM => "uhdmtchk_ref_term",
        RAW_UHDM_TCHK_TERM => "uhdmtchk_term",
        RAW_UHDM_TCHK_TERMS => "uhdmtchk_terms",
        RAW_UHDM_TCHKS => "uhdmtchks",
        RAW_UHDM_TF_CALL => "uhdmtf_call",
        RAW_UHDM_TF_CALL_ARGS => "uhdmtf_call_args",
        RAW_UHDM_THREAD_OBJ => "uhdmthread_obj",
        RAW_UHDM_THREADS => "uhdmthreads",
        RAW_UHDM_TIME_NET => "uhdmtime_net",
        RAW_UHDM_TIME_TYPESPEC => "uhdmtime_typespec",
        RAW_UHDM_TIME_VAR => "uhdmtime_var",
        RAW_UHDM_TYPE_PARAMETER => "uhdmtype_parameter",
        RAW_UHDM_TYPEDEF_ALIAS => "uhdmtypedef_alias",
        RAW_UHDM_TYPESPEC => "uhdmtypespec",
        RAW_UHDM_TYPESPEC_MEMBER => "uhdmtypespec_member",
        RAW_UHDM_TYPESPECS => "uhdmtypespecs",
        RAW_UHDM_UDP => "uhdmudp",
        RAW_UHDM_UDP_ARRAY => "uhdmudp_array",
        RAW_UHDM_UDP_DEFN => "uhdmudp_defn",
        RAW_UHDM_UNION_TYPESPEC => "uhdmunion_typespec",
        RAW_UHDM_UNION_VAR => "uhdmunion_var",
        RAW_UHDM_UNSUPPORTED_EXPR => "uhdmunsupported_expr",
        RAW_UHDM_UNSUPPORTED_STMT => "uhdmunsupported_stmt",
        RAW_UHDM_UNSUPPORTED_TYPESPEC => "uhdmunsupported_typespec",
        RAW_UHDM_USER_SYSTF => "uhdmuser_systf",
        RAW_UHDM_VALUE_RANGE => "uhdmvalue_range",
        RAW_UHDM_VAR_BIT => "uhdmvar_bit",
        RAW_UHDM_VAR_BITS => "uhdmvar_bits",
        RAW_UHDM_VAR_SELECT => "uhdmvar_select",
        RAW_UHDM_VAR_SELECTS => "uhdmvar_selects",
        RAW_UHDM_VARIABLE => "uhdmvariable",
        RAW_UHDM_VARIABLE_DRIVERS => "uhdmvariable_drivers",
        RAW_UHDM_VARIABLE_DRIVERS_GROUP => "uhdmvariable_drivers_group",
        RAW_UHDM_VARIABLE_LOADS => "uhdmvariable_loads",
        RAW_UHDM_VARIABLE_LOADS_GROUP => "uhdmvariable_loads_group",
        RAW_UHDM_VARIABLES => "uhdmvariables",
        RAW_UHDM_VARIABLES_OPERATION_GROUP => "uhdmvariables_operation_group",
        RAW_UHDM_VIRTUAL_INTERFACE_VAR => "uhdmvirtual_interface_var",
        RAW_UHDM_VIRTUAL_INTERFACE_VARS => "uhdmvirtual_interface_vars",
        RAW_UHDM_VOID_TYPESPEC => "uhdmvoid_typespec",
        RAW_UHDM_WAIT_FORK => "uhdmwait_fork",
        RAW_UHDM_WAIT_STMT => "uhdmwait_stmt",
        RAW_UHDM_WAITS => "uhdmwaits",
        RAW_UHDM_WEIGHT => "uhdmweight",
        RAW_UHDM_WHILE_STMT => "uhdmwhile_stmt",
        RAW_UHDM_WIDTH_EXPR => "uhdmwidth_expr",
        RAW_UHDM_WITH => "uhdmwith",
        _ => "<unknown>",
    }
}
